### ISSUE TITLE
multiple:false doesn't seem to be honored

### ISSUE THREAD

**Issue by eri-trabiccolo** [gocodebox/lifterlms-lite-lms-progress-tracker#23]
### Reproduction steps

+ Add a lifterlms lite lms block
+ Add another lifterlms lite lms block

### Expected behavior

+ I expected to not be able to even find that block to be added, and for sure not to be able to add it

### Actual behavior

+ I could add another instance of the block

**Comment by thomasplevy** [comment]
multiple belongs in the `supports` array, not as a top-level sections, fix incoming

**Comment by thomasplevy** [comment]
nevermind you got it

**Comment by eri-trabiccolo** [comment]
oh was already doing it 👍
yeah I thought it was that but I tested with `support` instead of `supports` and didn't worked either, then I opened this, then i realized the error :D
