### ISSUE TITLE
Add Images to Repo Page

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms-lite-lms-progress-tracker#31]
Add Images to Repo Page

![Add Lite LMS Progress Tracker By LifterLMS](https://user-images.githubusercontent.com/12163552/90295679-9c0f7080-de57-11ea-8e28-ee08123f5412.png)
![Allow Any Post or Page To Be Tracked (1)](https://user-images.githubusercontent.com/12163552/90295681-9ca80700-de57-11ea-8b08-29c8ad968e5e.png)
![Allow Progress Tracking Through  Your Website Content](https://user-images.githubusercontent.com/12163552/90295683-9d409d80-de57-11ea-8124-c20e6a474c0c.png)
![Allow Users To Reset Their Progress On Conttent](https://user-images.githubusercontent.com/12163552/90295684-9dd93400-de57-11ea-8344-833296953f2f.png)
![Create  Cuper Simple Online Courses And Learning Paths](https://user-images.githubusercontent.com/12163552/90295686-9e71ca80-de57-11ea-976f-c25292b62a93.png)
![Display Custom Messages Before And After Content Is Marked Complete](https://user-images.githubusercontent.com/12163552/90295689-9f0a6100-de57-11ea-8e4c-cc201e803e13.png)
![Link Content Together To Create Flow ](https://user-images.githubusercontent.com/12163552/90295692-9fa2f780-de57-11ea-932a-e07092e37a6b.png)

**Comment by thomasplevy** [comment]
@chrisbadgett screenshots come with a description / caption for each screenshot (shown below the screenshot in the repo)

Would you please write the captions you'd like for each screenshot

You can add the captions as a numbered list in this file: https://github.com/gocodebox/lifterlms-lite-lms-progress-tracker/blob/trunk/.wordpress-org/readme/screenshots.md

The screenshots (when actually added to the plugin repo) will be uploaded as screenshot-1.jpg, screenshot-2.jpg, etc... The numbers in the list correspond to the number of the screenshot. Keep that in mind when adding the screenshot descriptions!

**Comment by thomasplevy** [comment]
@chrisbadgett I've added the screenshots in the order you uploaded them, you can see them in this directory: https://github.com/gocodebox/lifterlms-lite-lms-progress-tracker/tree/trunk/.wordpress-org/assets

Let me know if they need to be re-ordered and I'll rename them accordingly

**Comment by thomasplevy** [comment]
Assets have been published to wordpress.org but we need captions before they'll show up in the repo
