### ISSUE TITLE
Add Lite LMS Icon and Plugin Banner

### ISSUE THREAD

**Issue by chrisbadgett** [gocodebox/lifterlms-lite-lms-progress-tracker#32]
Add icon and banner to plugin repo listing

All brand assets are here: https://drive.google.com/drive/folders/1JT5C6PCsqJqyxAQVWJdg2-FpyBgdMGqw?usp=sharing

### Banner

![Lite LMS Banner](https://user-images.githubusercontent.com/12163552/91584685-00830300-e921-11ea-943c-a8d641b839ba.png)

### Icon

![Lite LMS Icon](https://user-images.githubusercontent.com/12163552/91584812-30320b00-e921-11ea-9fbb-93d00acc61a3.png)

**Comment by thomasplevy** [comment]
@chrisbadgett can we get an SVG version of the icon to use as per the icon guidelines at https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#plugin-icons

Also it's best to have the source on hand anyway please (for both the banner and the icon)

**Comment by chrisbadgett** [comment]
### Banner

SVG & Design Files:

[LiteLMS Progress Tracker Banner.zip](https://github.com/gocodebox/lifterlms-lite-lms-progress-tracker/files/5195347/LiteLMS.Progress.Tracker.Banner.zip)

### Icon:

SVG & Design Files:

[LiteLMS Progress Tracker Icon.zip](https://github.com/gocodebox/lifterlms-lite-lms-progress-tracker/files/5195359/LiteLMS.Progress.Tracker.Icon.zip)
